
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydata?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: com.documendation.designpatterns.entity
#  mapperLocations: classpath:mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml

